@startuml
!define RECTANGLE class
!define ENTITY class

RECTANGLE Animal {
  id: Int
  dib: String
  raza: String
  classificationId: Int
  edad: Int
  articles: Article[]
}

RECTANGLE Article {
  id: Int
  name: String
  description: String?
  price: Float
  imagen: String?
  weightKg: Float?
  categoryId: Int
  category: Category
  animal: Animal
  parent: Article
  parentId: Int
  children: Article[]
  animalId: Int
}

RECTANGLE Classification {
  id: Int
  name: String
  description: String?
  animals: Animal[]
}

RECTANGLE Results {
  articles: Article[]
  MaxWeightKg: Int
  MinWeightKg: Int
  MediumWeightKg: Int
  MaxPrice: Int
  MinPrice: Int
  MediumPrice: Int
  Quantity: Int
}


Animal --|{ Article
Article --o{ Article: parent
Article --o{ Article: children
Article --o{ Classification
Classification --|{ Animal
Results --|{ Article
Classification --o{ Results
@enduml
