import { Inter, Nabla } from 'next/font/google'
import './globals.css'
import Navbar from './Navbar'
import { NextUIProvider } from '@nextui-org/react';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextUIProvider>
        <Navbar />
      </NextUIProvider>

      <body className={inter.className}>{children}</body> 
    </html>
  )
}
